id = "genexpr"
name = "Genexpr"
version = "0.1.0"
schema_version = 1
authors = ["Isabel Kasprsikie <mail@isabelgk.com>"]
description = "Genexpr support"
repository = "https://github.com/isabelgk/genexpr-zed"

[grammars.genexpr]
repository = "https://github.com/isabelgk/tree-sitter-genexpr"
rev = "452ebd11039dff78d76a7fca7e046fbfb54a0246"
